#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'
import { cancelRun, loadRunStatus, runTaskPlan } from './core/scheduler.mjs'

const server = new McpServer({
  name: 'subagent-control-protocol',
  version: '0.2.0',
  instructions: [
    'Use this MCP server when Codex should act as the controller and delegate bounded work to Claude Code CLI subagents.',
    'Use subagent_run_task for one task, or subagent_run_many for dependency-aware parallel plans.',
    'Always inspect structuredContent.runSummary before treating delegated work as complete.',
    'Run directories contain controller-readable prompts, raw outputs, normalized task results, and run-summary.json.',
  ].join(' '),
})

const permissionMode = z.enum([
  'acceptEdits',
  'auto',
  'bypassPermissions',
  'default',
  'dontAsk',
  'plan',
])

// Lifecycle status for a single task result. `completed`/`partial` come from the
// subagent's own JSON; `failed`/`timed_out` are imposed by the runner when the
// CLI exits non-zero or exceeds its timeout; `skipped` is set when a dependency
// did not reach a completed/partial state; `cancelled` is set when a run stops
// before a pending task starts or an active process is killed by cancellation.
const taskStatus = z
  .enum(['completed', 'partial', 'blocked', 'failed', 'skipped', 'timed_out', 'cancelled'])
  .describe('Terminal task lifecycle status.')

const taskShape = {
  id: z.string().regex(/^[A-Za-z0-9._-]+$/).optional().describe('Stable task id. Generated by the controller when omitted.'),
  title: z.string().optional().describe('Human-readable title for the delegated task.'),
  kind: z.enum(['plan', 'implement', 'review', 'verify', 'research', 'other']).optional(),
  prompt: z.string().min(1).describe('Actual delegated instruction for Claude Code CLI.'),
  dependsOn: z.array(z.string()).optional(),
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const defaultsShape = {
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const commonRunShape = {
  workspace: z.string().optional().describe('Workspace where Claude Code should run. Defaults to the MCP process cwd.'),
  outputDir: z.string().optional().describe('Directory for persistent run artifacts. Defaults to <workspace>/.subagent-runs.'),
  concurrency: z.number().int().positive().max(16).optional(),
  dryRun: z.boolean().optional().describe('Write prompts and command previews without invoking Claude Code CLI.'),
  claudeExecutable: z.string().optional().describe('Override Claude executable path. Env fallback: CLAUDE_BIN or CLAUDE_CODE_COMMAND.'),
  claudeBaseArgs: z.array(z.string()).optional().describe('Advanced: raw args inserted before Claude CLI flags, useful for tests or wrappers.'),
  env: z.record(z.string(), z.string()).optional().describe('Extra environment variables passed to Claude Code CLI.'),
}

// Output schema for a normalized task result. `id`, `title`, and `status` are
// always present; the remaining fields depend on how the task ended (see
// taskStatus). Kept permissive so dry-run, failed, skipped, and full results
// all validate against the same contract.
const taskResultShape = {
  id: z.string(),
  title: z.string(),
  status: taskStatus,
  startedAt: z.string().optional(),
  endedAt: z.string().optional(),
  taskDir: z.string().optional(),
  exitCode: z.number().int().optional(),
  signal: z.string().nullable().optional(),
  timedOut: z.boolean().optional(),
  cancelled: z.boolean().optional(),
  durationMs: z.number().int().optional(),
  reason: z.string().optional().describe('Present when status is "skipped".'),
  error: z.string().optional().describe('Present when status is "failed".'),
  command: z.string().optional(),
  parsed: z.any().optional().describe('Normalized agent-result object when the CLI produced parseable JSON.'),
  rawParsed: z.any().optional(),
  usage: z.any().optional(),
  measuredUsageSummary: z.string().optional(),
}

const activeProcessShape = {
  runId: z.string(),
  taskId: z.string(),
  title: z.string(),
  pid: z.number().int(),
  startedAt: z.string(),
}

// Machine-readable error detail returned inside the error envelope. Present on
// every tool's outputSchema so structured errors validate the same way success
// results do (the SDK skips server-side validation for isError results, but
// validating clients still check structuredContent against outputSchema).
const errorDetailShape = {
  code: z.string(),
  message: z.string(),
  stack: z.string().optional(),
}

// Output schema for a run summary. summarizeRun always populates every field
// below; `tasks` carries one taskResultShape per task in input order.
const runSummaryShape = {
  runId: z.string(),
  runDir: z.string(),
  startedAt: z.string(),
  endedAt: z.string(),
  workspace: z.string(),
  concurrency: z.number().int(),
  maxParallelObserved: z.number().int(),
  dryRun: z.boolean(),
  totalTasks: z.number().int(),
  completedTasks: z.number().int(),
  partialTasks: z.number().int(),
  blockedTasks: z.number().int(),
  failedTasks: z.number().int(),
  skippedTasks: z.number().int(),
  cancelledTasks: z.number().int(),
  timedOutTasks: z.number().int(),
  tasks: z.array(z.object(taskResultShape)),
}

// Shared envelope for every tool. `ok` discriminates success (true, with the
// tool's payload) from error (false, with `error`). Payload and error fields
// are all optional so a single schema validates both branches for clients that
// enforce outputSchema on structuredContent. Success fields:
//   - run tools: runSummary, results, and result (single task, run_task only)
//   - status:    mode, active, summary | (outputDir, runs)
//   - cancel:    runId, cancelledProcesses
const runOutputShape = {
  ok: z.boolean(),
  runSummary: z.object(runSummaryShape).optional(),
  results: z.array(z.object(taskResultShape)).optional(),
  result: z.object(taskResultShape).optional().describe('Single task; present only for subagent_run_task.'),
  error: z.object(errorDetailShape).optional(),
}

const runManyOutputShape = {
  ok: z.boolean(),
  runSummary: z.object(runSummaryShape).optional(),
  results: z.array(z.object(taskResultShape)).optional(),
  error: z.object(errorDetailShape).optional(),
}

const statusOutputShape = {
  ok: z.boolean(),
  mode: z.enum(['single', 'list']).optional(),
  active: z.array(z.object(activeProcessShape)).optional(),
  summary: z.object(runSummaryShape).optional().describe('Present when mode is "single".'),
  outputDir: z.string().optional().describe('Present when mode is "list".'),
  runs: z
    .array(z.record(z.string(), z.any()))
    .optional()
    .describe('Present when mode is "list"; entries are run summaries or { runDir, status: "incomplete_or_unreadable" }.'),
  error: z.object(errorDetailShape).optional(),
}

const cancelOutputShape = {
  ok: z.boolean(),
  runId: z.string().optional(),
  cancelledProcesses: z.number().int().optional(),
  error: z.object(errorDetailShape).optional(),
}

server.registerTool(
  'subagent_run_task',
  {
    title: 'Run One Claude Subagent Task',
    description: 'Run one bounded Claude Code CLI subagent task and return the normalized result to the controller. Returns { runSummary, results, result }; result is the single task. On failure returns a structured error object with isError=true.',
    inputSchema: {
      ...commonRunShape,
      ...taskShape,
    },
    outputSchema: runOutputShape,
  },
  async (input) => {
    try {
      const task = {
        id: input.id || 'task',
        title: input.title || input.id || 'Delegated task',
        kind: input.kind || 'other',
        prompt: input.prompt,
        dependsOn: [],
        ...pickTaskFields(input),
      }
      const runSummary = await runTaskPlan(
        { version: 1, tasks: [task] },
        pickRunOptions(input),
      )
      const results = runSummary.tasks
      return jsonToolResult({ runSummary, results, result: results[0] })
    } catch (error) {
      return errorToolResult(error, 'run_task_failed')
    }
  },
)

server.registerTool(
  'subagent_run_many',
  {
    title: 'Run Many Claude Subagent Tasks',
    description: 'Run a dependency-aware Claude Code CLI subagent plan with controller-selected concurrency. Returns { runSummary, results }; results is the full task array in input order. On failure returns a structured error object with isError=true.',
    inputSchema: {
      ...commonRunShape,
      defaults: z.object(defaultsShape).optional(),
      tasks: z.array(z.object({ ...taskShape, id: z.string().regex(/^[A-Za-z0-9._-]+$/), title: z.string() })).min(1),
    },
    outputSchema: runManyOutputShape,
  },
  async (input) => {
    try {
      const runSummary = await runTaskPlan(
        {
          version: 1,
          defaults: input.defaults,
          tasks: input.tasks,
        },
        pickRunOptions(input),
      )
      return jsonToolResult({ runSummary, results: runSummary.tasks })
    } catch (error) {
      return errorToolResult(error, 'run_many_failed')
    }
  },
)

server.registerTool(
  'subagent_status',
  {
    title: 'Read Subagent Run Status',
    description: 'Read one run-summary.json (mode "single") or list recent run summaries from an output directory (mode "list"). Both modes include the active-process list.',
    inputSchema: {
      runDir: z.string().optional(),
      outputDir: z.string().optional(),
      limit: z.number().int().positive().max(100).optional(),
    },
    outputSchema: statusOutputShape,
  },
  async (input) => {
    try {
      return jsonToolResult(await loadRunStatus(input))
    } catch (error) {
      return errorToolResult(error, 'status_failed')
    }
  },
)

server.registerTool(
  'subagent_cancel',
  {
    title: 'Cancel Active Subagent Run',
    description: 'Best-effort cancellation for Claude processes currently active in this MCP server process. Returns { runId, cancelledProcesses }.',
    inputSchema: {
      runId: z.string().min(1),
    },
    outputSchema: cancelOutputShape,
  },
  async (input) => {
    try {
      return jsonToolResult(await cancelRun(input.runId))
    } catch (error) {
      return errorToolResult(error, 'cancel_failed')
    }
  },
)

const transport = new StdioServerTransport()
await server.connect(transport)

function pickRunOptions(input) {
  return {
    workspace: input.workspace,
    outputDir: input.outputDir,
    concurrency: input.concurrency,
    dryRun: input.dryRun,
    claudeExecutable: input.claudeExecutable,
    claudeBaseArgs: input.claudeBaseArgs,
    env: input.env,
  }
}

function pickTaskFields(input) {
  return {
    model: input.model,
    effort: input.effort,
    timeoutMs: input.timeoutMs,
    permissionMode: input.permissionMode,
    addDirs: input.addDirs,
    allowedTools: input.allowedTools,
    disallowedTools: input.disallowedTools,
    tools: input.tools,
    systemPrompt: input.systemPrompt,
  }
}

function jsonToolResult(data) {
  const payload = { ok: true, ...data }
  return {
    structuredContent: payload,
    content: [
      {
        type: 'text',
        text: JSON.stringify(payload, null, 2),
      },
    ],
  }
}

// Structured error result. isError=true tells the client the tool failed while
// still returning a machine-readable error object in structuredContent; the SDK
// skips output-schema validation for isError results, so the error envelope is
// not constrained by the success outputSchema.
function errorToolResult(error, code) {
  const message = error instanceof Error ? error.message : String(error)
  const payload = {
    ok: false,
    error: {
      code: code || 'tool_error',
      message,
      ...(error instanceof Error && error.stack ? { stack: error.stack } : {}),
    },
  }
  return {
    isError: true,
    structuredContent: payload,
    content: [
      {
        type: 'text',
        text: JSON.stringify(payload, null, 2),
      },
    ],
  }
}
