#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'
import { cancelRun, loadRunStatus, runTaskPlan } from './core/scheduler.mjs'

const server = new McpServer({
  name: 'subagent-control-protocol',
  version: '0.2.0',
  instructions: [
    'Use this MCP server when Codex should act as the controller and delegate bounded work to Claude Code CLI subagents.',
    'Use subagent_run_task for one task, or subagent_run_many for dependency-aware parallel plans.',
    'Always inspect structuredContent.runSummary before treating delegated work as complete.',
    'Run directories contain controller-readable prompts, raw outputs, normalized task results, and run-summary.json.',
  ].join(' '),
})

const permissionMode = z.enum([
  'acceptEdits',
  'auto',
  'bypassPermissions',
  'default',
  'dontAsk',
  'plan',
])

const taskShape = {
  id: z.string().regex(/^[A-Za-z0-9._-]+$/).optional().describe('Stable task id. Generated by the controller when omitted.'),
  title: z.string().optional().describe('Human-readable title for the delegated task.'),
  kind: z.enum(['plan', 'implement', 'review', 'verify', 'research', 'other']).optional(),
  prompt: z.string().min(1).describe('Actual delegated instruction for Claude Code CLI.'),
  dependsOn: z.array(z.string()).optional(),
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  maxBudgetUsd: z.number().nonnegative().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const defaultsShape = {
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  maxBudgetUsd: z.number().nonnegative().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const commonRunShape = {
  workspace: z.string().optional().describe('Workspace where Claude Code should run. Defaults to the MCP process cwd.'),
  outputDir: z.string().optional().describe('Directory for persistent run artifacts. Defaults to <workspace>/.subagent-runs.'),
  concurrency: z.number().int().positive().max(16).optional(),
  dryRun: z.boolean().optional().describe('Write prompts and command previews without invoking Claude Code CLI.'),
  claudeExecutable: z.string().optional().describe('Override Claude executable path. Env fallback: CLAUDE_BIN or CLAUDE_CODE_COMMAND.'),
  claudeBaseArgs: z.array(z.string()).optional().describe('Advanced: raw args inserted before Claude CLI flags, useful for tests or wrappers.'),
  env: z.record(z.string(), z.string()).optional().describe('Extra environment variables passed to Claude Code CLI.'),
}

server.registerTool(
  'subagent_run_task',
  {
    title: 'Run One Claude Subagent Task',
    description: 'Run one bounded Claude Code CLI subagent task and return the normalized result to the controller.',
    inputSchema: {
      ...commonRunShape,
      ...taskShape,
    },
  },
  async (input) => {
    const task = {
      id: input.id || 'task',
      title: input.title || input.id || 'Delegated task',
      kind: input.kind || 'other',
      prompt: input.prompt,
      dependsOn: [],
      ...pickTaskFields(input),
    }
    const runSummary = await runTaskPlan(
      { version: 1, tasks: [task] },
      pickRunOptions(input),
    )
    return jsonToolResult({ runSummary, result: runSummary.tasks[0] })
  },
)

server.registerTool(
  'subagent_run_many',
  {
    title: 'Run Many Claude Subagent Tasks',
    description: 'Run a dependency-aware Claude Code CLI subagent plan with controller-selected concurrency.',
    inputSchema: {
      ...commonRunShape,
      defaults: z.object(defaultsShape).optional(),
      tasks: z.array(z.object({ ...taskShape, id: z.string().regex(/^[A-Za-z0-9._-]+$/), title: z.string() })).min(1),
    },
  },
  async (input) => {
    const runSummary = await runTaskPlan(
      {
        version: 1,
        defaults: input.defaults,
        tasks: input.tasks,
      },
      pickRunOptions(input),
    )
    return jsonToolResult({ runSummary })
  },
)

server.registerTool(
  'subagent_status',
  {
    title: 'Read Subagent Run Status',
    description: 'Read one run-summary.json or list recent run summaries from an output directory.',
    inputSchema: {
      runDir: z.string().optional(),
      outputDir: z.string().optional(),
      limit: z.number().int().positive().max(100).optional(),
    },
  },
  async (input) => jsonToolResult(await loadRunStatus(input)),
)

server.registerTool(
  'subagent_cancel',
  {
    title: 'Cancel Active Subagent Run',
    description: 'Best-effort cancellation for Claude processes currently active in this MCP server process.',
    inputSchema: {
      runId: z.string().min(1),
    },
  },
  async (input) => jsonToolResult(await cancelRun(input.runId)),
)

const transport = new StdioServerTransport()
await server.connect(transport)

function pickRunOptions(input) {
  return {
    workspace: input.workspace,
    outputDir: input.outputDir,
    concurrency: input.concurrency,
    dryRun: input.dryRun,
    claudeExecutable: input.claudeExecutable,
    claudeBaseArgs: input.claudeBaseArgs,
    env: input.env,
  }
}

function pickTaskFields(input) {
  return {
    model: input.model,
    effort: input.effort,
    timeoutMs: input.timeoutMs,
    maxBudgetUsd: input.maxBudgetUsd,
    permissionMode: input.permissionMode,
    addDirs: input.addDirs,
    allowedTools: input.allowedTools,
    disallowedTools: input.disallowedTools,
    tools: input.tools,
    systemPrompt: input.systemPrompt,
  }
}

function jsonToolResult(data) {
  return {
    structuredContent: data,
    content: [
      {
        type: 'text',
        text: JSON.stringify(data, null, 2),
      },
    ],
  }
}
