#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'
import { executeCleanup, planCleanup } from './core/cleanup.mjs'
import { cancelRun, collectRun, loadRunStatus, runTaskPlan, startTaskPlan, watchRun } from './core/scheduler.mjs'

const server = new McpServer({
  name: 'subagent-control-protocol',
  version: '0.3.4',
  instructions: [
    'Use this MCP server when Codex should act as the controller and delegate bounded work to Claude Code CLI subagents.',
    'Codex is the controller: it owns decomposition, dependency analysis, parallelism, and review; this MCP server is only the execution layer and never decides decomposition or parallelism on its own.',
    'Before delegating construction tasks, build a todoList that, for each task, marks its dependencies, whether it is parallelizable, and the files it owns (exclusive file ownership prevents conflicting edits).',
    'Dispatch parallelizable work through subagent_run_many (dependency-aware) and keep strictly serial work on subagent_run_task.',
    'As a controller-side convention enforced by the orchestrator Skill, after implementation always add two read-only review subagents: one reviewing from a software-engineering perspective (correctness, structure, tests, risks) and one from a real-user perspective (does it actually solve the user request, is it usable). Reviewers must not edit files.',
    'Use subagent_run_task for one task, or subagent_run_many for dependency-aware parallel plans.',
    'Always inspect structuredContent.runSummary before treating delegated work as complete.',
    'Run directories contain controller-readable prompts, raw outputs, normalized task results, run-summary.json, and may include an events.jsonl append-only log of lifecycle/heartbeat events emitted by the runner.',
    'Prefer subagent_status for structured run status and event summaries (including heartbeats) rather than reading raw stdout/stderr files by default; subagent_status accepts recentEventsLimit to bound the number of recent event entries returned.',
    'For long-running plans, use subagent_start to launch a dependency-aware plan in the background and return immediately with start info (runId/runDir), then use subagent_collect to fetch the final run summary or interim progress; subagent_start/subagent_collect are the async counterpart to the blocking subagent_run_many.',
    'Use subagent_watch for controller-friendly health checks over running plans, including stalled/slow heartbeat detection and suggested controller actions.',
    'Use subagent_cleanup to safely plan or execute retention cleanup for run artifact directories; dryRun defaults to true.',
  ].join(' '),
})

const permissionMode = z.enum([
  'acceptEdits',
  'auto',
  'bypassPermissions',
  'default',
  'dontAsk',
  'plan',
])

// Lifecycle status for a single task result. `completed`/`partial` come from the
// subagent's own JSON; `failed`/`timed_out` are imposed by the runner when the
// CLI exits non-zero or exceeds its timeout; `skipped` is set when a dependency
// did not reach a completed/partial state; `cancelled` is set when a run stops
// before a pending task starts or an active process is killed by cancellation.
const taskStatus = z
  .enum(['completed', 'partial', 'blocked', 'failed', 'skipped', 'timed_out', 'cancelled'])
  .describe('Terminal task lifecycle status.')

const taskShape = {
  id: z.string().regex(/^[A-Za-z0-9._-]+$/).optional().describe('Stable task id. Generated by the controller when omitted.'),
  title: z.string().optional().describe('Human-readable title for the delegated task.'),
  kind: z.enum(['plan', 'implement', 'review', 'verify', 'research', 'other']).optional(),
  prompt: z.string().min(1).describe('Actual delegated instruction for Claude Code CLI.'),
  dependsOn: z.array(z.string()).optional(),
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const defaultsShape = {
  model: z.string().optional(),
  effort: z.enum(['low', 'medium', 'high', 'xhigh', 'max']).optional(),
  timeoutMs: z.number().int().positive().optional(),
  permissionMode: permissionMode.optional(),
  addDirs: z.array(z.string()).optional(),
  allowedTools: z.array(z.string()).optional(),
  disallowedTools: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  systemPrompt: z.string().optional(),
}

const commonRunShape = {
  workspace: z.string().optional().describe('Workspace where Claude Code should run. Defaults to the MCP process cwd.'),
  outputDir: z.string().optional().describe('Directory for persistent run artifacts. Defaults to <workspace>/.subagent-runs.'),
  concurrency: z.number().int().positive().max(16).optional(),
  dryRun: z.boolean().optional().describe('Write prompts and command previews without invoking Claude Code CLI.'),
  claudeExecutable: z.string().optional().describe('Override Claude executable path. Env fallback: CLAUDE_BIN or CLAUDE_CODE_COMMAND.'),
  claudeBaseArgs: z.array(z.string()).optional().describe('Advanced: raw args inserted before Claude CLI flags, useful for tests or wrappers.'),
  env: z.record(z.string(), z.string()).optional().describe('Extra environment variables passed to Claude Code CLI.'),
}

// Output schema for a normalized task result. `id`, `title`, and `status` are
// always present; the remaining fields depend on how the task ended (see
// taskStatus). Kept permissive so dry-run, failed, skipped, and full results
// all validate against the same contract.
const taskResultShape = {
  id: z.string(),
  title: z.string(),
  status: taskStatus,
  startedAt: z.string().optional(),
  endedAt: z.string().optional(),
  taskDir: z.string().optional(),
  exitCode: z.number().int().optional(),
  signal: z.string().nullable().optional(),
  timedOut: z.boolean().optional(),
  cancelled: z.boolean().optional(),
  durationMs: z.number().int().optional(),
  reason: z.string().optional().describe('Present when status is "skipped".'),
  error: z.string().optional().describe('Present when status is "failed".'),
  command: z.string().optional(),
  parsed: z.any().optional().describe('Normalized agent-result object when the CLI produced parseable JSON.'),
  rawParsed: z.any().optional(),
  usage: z.any().optional(),
  measuredUsageSummary: z.string().optional(),
  eventLogPath: z.string().optional().describe('Path to the task/run events.jsonl log when event tracking is enabled; absent for legacy runs.'),
  lastHeartbeatAt: z.string().optional().describe('ISO timestamp of the most recent runner heartbeat, when available.'),
  lastEventAt: z.string().optional().describe('ISO timestamp of the most recent recorded lifecycle event, when available.'),
  events: z.any().optional().describe('Compact per-task event summary attached by subagent_status in single-run mode.'),
}

const activeProcessShape = {
  runId: z.string(),
  taskId: z.string(),
  title: z.string(),
  pid: z.number().int(),
  startedAt: z.string(),
  eventLogPath: z.string().optional().describe('Path to this active task events.jsonl log, when event tracking is enabled.'),
  lastEventAt: z.string().optional().describe('ISO timestamp of the most recent lifecycle event for the active process, when available.'),
}

// Machine-readable error detail returned inside the error envelope. Present on
// every tool's outputSchema so structured errors validate the same way success
// results do (the SDK skips server-side validation for isError results, but
// validating clients still check structuredContent against outputSchema).
const errorDetailShape = {
  code: z.string(),
  message: z.string(),
  stack: z.string().optional(),
}

// Output schema for a run summary. summarizeRun always populates every field
// below; `tasks` carries one taskResultShape per task in input order.
const runSummaryShape = {
  runId: z.string(),
  runDir: z.string(),
  startedAt: z.string(),
  endedAt: z.string(),
  workspace: z.string(),
  concurrency: z.number().int(),
  maxParallelObserved: z.number().int(),
  dryRun: z.boolean(),
  totalTasks: z.number().int(),
  completedTasks: z.number().int(),
  partialTasks: z.number().int(),
  blockedTasks: z.number().int(),
  failedTasks: z.number().int(),
  skippedTasks: z.number().int(),
  cancelledTasks: z.number().int(),
  timedOutTasks: z.number().int(),
  tasks: z.array(z.object(taskResultShape)),
  ownershipViolations: z.array(z.record(z.string(), z.any())).optional(),
  ownershipWarnings: z.array(z.record(z.string(), z.any())).optional(),
}

// Shared envelope for every tool. `ok` discriminates success (true, with the
// tool's payload) from error (false, with `error`). Payload and error fields
// are all optional so a single schema validates both branches for clients that
// enforce outputSchema on structuredContent. Success fields:
//   - run tools: runSummary, results, and result (single task, run_task only)
//   - status:    mode, active, summary | (outputDir, runs)
//   - cancel:    runId, cancelledProcesses
const runOutputShape = {
  ok: z.boolean(),
  runSummary: z.object(runSummaryShape).optional(),
  results: z.array(z.object(taskResultShape)).optional(),
  result: z.object(taskResultShape).optional().describe('Single task; present only for subagent_run_task.'),
  error: z.object(errorDetailShape).optional(),
}

const runManyOutputShape = {
  ok: z.boolean(),
  runSummary: z.object(runSummaryShape).optional(),
  results: z.array(z.object(taskResultShape)).optional(),
  error: z.object(errorDetailShape).optional(),
}

const statusOutputShape = {
  ok: z.boolean(),
  mode: z.enum(['single', 'list']).optional(),
  active: z.array(z.object(activeProcessShape)).optional(),
  summary: z.record(z.string(), z.any()).optional().describe('Present when mode is "single"; may be a full run-summary.json or a minimal in-progress summary before run-summary.json exists.'),
  recentEvents: z.array(z.record(z.string(), z.any())).optional().describe('Bounded, trimmed recent events from task events.jsonl files in single-run mode.'),
  taskEvents: z.array(z.record(z.string(), z.any())).optional().describe('Per-task compact event summaries in single-run mode.'),
  health: z.record(z.string(), z.any()).optional().describe('Run health summary derived from events/heartbeats.'),
  controllerSummary: z.record(z.string(), z.any()).optional().describe('Compact controller-facing summary for decision making.'),
  statusEvents: z.record(z.string(), z.any()).optional().describe('Compact event metadata in list mode.'),
  outputDir: z.string().optional().describe('Present when mode is "list".'),
  runs: z
    .array(z.record(z.string(), z.any()))
    .optional()
    .describe('Present when mode is "list"; entries are run summaries or { runDir, status: "incomplete_or_unreadable" }.'),
  error: z.object(errorDetailShape).optional(),
}

const cancelOutputShape = {
  ok: z.boolean(),
  runId: z.string().optional(),
  cancelledProcesses: z.number().int().optional(),
  error: z.object(errorDetailShape).optional(),
}

// Output schema for subagent_start. The start info comes straight from
// startTaskPlan; every field is optional so the schema validates regardless of
// how much progress information the runner has populated at start time. This is
// the async counterpart to runManyOutputShape: it returns immediately with
// enough to locate and later collect the run (runId/runDir), not the results.
const startOutputShape = {
  ok: z.boolean(),
  runId: z.string().optional(),
  runDir: z.string().optional(),
  outputDir: z.string().optional(),
  startedAt: z.string().optional(),
  workspace: z.string().optional(),
  status: z.string().optional().describe('Start status, e.g. "running".'),
  totalTasks: z.number().int().optional(),
  concurrency: z.number().int().optional(),
  dryRun: z.boolean().optional(),
  active: z.array(z.record(z.string(), z.any())).optional().describe('Processes already started at return time, when available.'),
  summary: z.record(z.string(), z.any()).optional().describe('Initial/progress summary when available; absent until the runner has one.'),
  error: z.object(errorDetailShape).optional(),
}

// Output schema for subagent_collect. Mirrors the collectRun result: a run
// locator (runId/runDir), a done flag and run-level status, the full run
// summary when present (otherwise a minimal in-progress summary), per-task
// results, and a bounded recent-events window. All payload fields optional so a
// not-yet-complete run validates the same way a finished one does.
const collectOutputShape = {
  ok: z.boolean(),
  runId: z.string().optional(),
  runDir: z.string().optional(),
  done: z.boolean().optional().describe('True once the run has reached a terminal state.'),
  status: z.string().optional().describe('Run-level status, e.g. "running", "completed", "failed", "cancelled".'),
  mode: z.enum(['single', 'list']).optional().describe('Present for in-progress status payloads borrowed from subagent_status.'),
  summary: z.record(z.string(), z.any()).optional().describe('Full run-summary.json when available, otherwise a minimal in-progress summary.'),
  runSummary: z.record(z.string(), z.any()).optional().describe('Alias for a terminal run summary when implementations choose to expose it separately.'),
  results: z.array(z.object(taskResultShape)).optional(),
  recentEvents: z.array(z.record(z.string(), z.any())).optional().describe('Bounded recent event window from task events.jsonl files, when requested.'),
  taskEvents: z.array(z.record(z.string(), z.any())).optional().describe('Per-task compact event summaries for in-progress runs.'),
  active: z.array(z.record(z.string(), z.any())).optional().describe('Active Claude child processes for this run, when known.'),
  health: z.record(z.string(), z.any()).optional().describe('Run health summary derived from events/heartbeats.'),
  controllerSummary: z.record(z.string(), z.any()).optional().describe('Compact controller-facing summary for decision making.'),
  error: z.object(errorDetailShape).optional(),
}

const watchOutputShape = {
  ...collectOutputShape,
  suggestedAction: z.string().optional().describe('Controller action hint based on current run health.'),
}

const cleanupOutputShape = {
  ok: z.boolean(),
  outputDir: z.string().optional(),
  dryRun: z.boolean().optional(),
  options: z.record(z.string(), z.any()).optional(),
  plan: z.record(z.string(), z.any()).optional(),
  runs: z.array(z.record(z.string(), z.any())).optional(),
  summary: z.record(z.string(), z.any()).optional(),
  deletedRuns: z.array(z.record(z.string(), z.any())).optional(),
  keptRuns: z.array(z.record(z.string(), z.any())).optional(),
  reclaimedBytes: z.number().optional(),
  errors: z.array(z.record(z.string(), z.any())).optional(),
  error: z.object(errorDetailShape).optional(),
}

server.registerTool(
  'subagent_run_task',
  {
    title: 'Run One Claude Subagent Task',
    description: 'Run one bounded Claude Code CLI subagent task and return the normalized result to the controller. Returns { runSummary, results, result }; result is the single task. On failure returns a structured error object with isError=true.',
    inputSchema: {
      ...commonRunShape,
      ...taskShape,
    },
    outputSchema: runOutputShape,
  },
  async (input) => {
    try {
      const task = {
        id: input.id || 'task',
        title: input.title || input.id || 'Delegated task',
        kind: input.kind || 'other',
        prompt: input.prompt,
        dependsOn: [],
        ...pickTaskFields(input),
      }
      const runSummary = await runTaskPlan(
        { version: 1, tasks: [task] },
        pickRunOptions(input),
      )
      const results = runSummary.tasks
      return jsonToolResult({ runSummary, results, result: results[0] })
    } catch (error) {
      return errorToolResult(error, 'run_task_failed')
    }
  },
)

server.registerTool(
  'subagent_run_many',
  {
    title: 'Run Many Claude Subagent Tasks',
    description: 'Run a dependency-aware Claude Code CLI subagent plan with controller-selected concurrency. Returns { runSummary, results }; results is the full task array in input order. On failure returns a structured error object with isError=true.',
    inputSchema: {
      ...commonRunShape,
      defaults: z.object(defaultsShape).optional(),
      tasks: z.array(z.object({ ...taskShape, id: z.string().regex(/^[A-Za-z0-9._-]+$/), title: z.string() })).min(1),
    },
    outputSchema: runManyOutputShape,
  },
  async (input) => {
    try {
      const runSummary = await runTaskPlan(
        {
          version: 1,
          defaults: input.defaults,
          tasks: input.tasks,
        },
        pickRunOptions(input),
      )
      return jsonToolResult({ runSummary, results: runSummary.tasks })
    } catch (error) {
      return errorToolResult(error, 'run_many_failed')
    }
  },
)

server.registerTool(
  'subagent_start',
  {
    title: 'Start Subagent Plan Asynchronously',
    description: 'Start a dependency-aware Claude Code CLI subagent plan in the background and return immediately with structured start info (runId/runDir). This is the non-blocking counterpart to subagent_run_many: it does not wait for tasks to finish. Use subagent_collect to fetch the final run summary or interim progress. Input shape matches subagent_run_many (common run options + optional defaults + tasks). On failure returns a structured error object with isError=true.',
    inputSchema: {
      ...commonRunShape,
      defaults: z.object(defaultsShape).optional(),
      tasks: z.array(z.object({ ...taskShape, id: z.string().regex(/^[A-Za-z0-9._-]+$/), title: z.string() })).min(1),
    },
    outputSchema: startOutputShape,
  },
  async (input) => {
    try {
      const startInfo = await startTaskPlan(
        {
          version: 1,
          defaults: input.defaults,
          tasks: input.tasks,
        },
        pickRunOptions(input),
      )
      return jsonToolResult(startInfo)
    } catch (error) {
      return errorToolResult(error, 'start_failed')
    }
  },
)

server.registerTool(
  'subagent_collect',
  {
    title: 'Collect Subagent Run Result',
    description: 'Collect the final run summary or interim progress for a run started with subagent_start. Accepts runId and/or runDir (plus outputDir to disambiguate) and returns the collectRun result: run locator, done flag, run-level status, full run summary when available (otherwise a minimal in-progress summary), per-task results, and a bounded recent-events window when recentEventsLimit is supplied. Use this for final collection or progress polling; it does not start new work. On failure returns a structured error object with isError=true.',
    inputSchema: {
      runId: z.string().optional().describe('Run id to collect. When omitted, runDir is used to locate the run.'),
      runDir: z.string().optional().describe('Run directory to collect. Used directly, or to resolve a runId.'),
      workspace: z.string().optional().describe('Workspace used to resolve the default outputDir when runDir and outputDir are not supplied. Defaults to the MCP server working directory.'),
      outputDir: z.string().optional().describe('Output directory to resolve a runId when runDir is not supplied. Defaults to <workspace>/.subagent-runs.'),
      recentEventsLimit: z.number().int().positive().max(1000).optional().describe('Maximum number of recent event entries (from events.jsonl) to return. Omitted means no recent-events window is requested.'),
      staleHeartbeatMs: z.number().int().positive().optional().describe('Heartbeat age threshold for stalled detection.'),
      slowEventMs: z.number().int().positive().optional().describe('Event age threshold for slow detection.'),
      includeControllerSummary: z.boolean().optional().describe('Set false to omit controllerSummary from polling responses.'),
    },
    outputSchema: collectOutputShape,
  },
  async (input) => {
    try {
      const collected = await collectRun(input)
      return jsonToolResult(collected)
    } catch (error) {
      return errorToolResult(error, 'collect_failed')
    }
  },
)

server.registerTool(
  'subagent_watch',
  {
    title: 'Watch Subagent Run Health',
    description: 'Read controller-friendly health for a subagent run without starting new work. Accepts runId and/or runDir plus outputDir/workspace and returns collect/status data, heartbeat-derived health, a compact controllerSummary, and a suggestedAction such as continue_waiting or inspect_or_cancel_stalled_tasks.',
    inputSchema: {
      runId: z.string().optional().describe('Run id to watch. When omitted, runDir is used.'),
      runDir: z.string().optional().describe('Run directory to watch.'),
      workspace: z.string().optional().describe('Workspace used to resolve default outputDir when needed.'),
      outputDir: z.string().optional().describe('Output directory to resolve runId when runDir is not supplied.'),
      recentEventsLimit: z.number().int().positive().max(1000).optional(),
      staleHeartbeatMs: z.number().int().positive().optional().describe('Heartbeat age threshold for stalled detection.'),
      slowEventMs: z.number().int().positive().optional().describe('Event age threshold for slow detection.'),
      compact: z.boolean().optional().describe('Return a compact health payload instead of the full collect-shaped response.'),
      healthOnly: z.boolean().optional().describe('Alias for compact.'),
      includeControllerSummary: z.boolean().optional().describe('Set false to omit controllerSummary from the watch payload.'),
      includeTaskEvents: z.boolean().optional().describe('When compact is true, include per-task event summaries. Defaults to false.'),
    },
    outputSchema: watchOutputShape,
  },
  async (input) => {
    try {
      return jsonToolResult(await watchRun(input))
    } catch (error) {
      return errorToolResult(error, 'watch_failed')
    }
  },
)

server.registerTool(
  'subagent_cleanup',
  {
    title: 'Clean Up Subagent Run Artifacts',
    description: 'Plan or execute safe retention cleanup for subagent run artifact directories. dryRun defaults to true. Deletion is restricted to direct child run directories under outputDir.',
    inputSchema: {
      workspace: z.string().optional().describe('Workspace used to resolve default outputDir when outputDir is omitted.'),
      outputDir: z.string().optional().describe('Run artifact output directory. Defaults to <workspace>/.subagent-runs.'),
      dryRun: z.boolean().optional().describe('When true, only report what would be deleted. Defaults to true.'),
      maxAgeDays: z.number().nonnegative().optional(),
      maxRuns: z.number().int().nonnegative().optional(),
      maxBytes: z.number().int().nonnegative().optional(),
      keepFailed: z.boolean().optional().describe('Keep failed runs even when retention rules match. Defaults to true.'),
      includeIncomplete: z.boolean().optional().describe('Allow incomplete/in-progress-looking runs to be deleted. Defaults to false.'),
    },
    outputSchema: cleanupOutputShape,
  },
  async (input) => {
    try {
      const outputDir = input.outputDir || `${input.workspace || process.cwd()}/.subagent-runs`
      const options = { ...input, outputDir }
      if (input.dryRun === false) {
        return jsonToolResult(await executeCleanup(options))
      }
      const plan = await planCleanup({ ...options, dryRun: true })
      return jsonToolResult({ ...plan, plan })
    } catch (error) {
      return errorToolResult(error, 'cleanup_failed')
    }
  },
)

server.registerTool(
  'subagent_status',
  {
    title: 'Read Subagent Run Status',
    description: 'Read one run-summary.json (mode "single") or list recent run summaries from an output directory (mode "list"). Both modes include the active-process list. When event tracking is available, results include heartbeat timestamps (lastHeartbeatAt/lastEventAt) and, in single mode, recent event summaries bounded by recentEventsLimit. Prefer this tool for structured status and events over reading raw stdout/stderr files directly.',
    inputSchema: {
      runDir: z.string().optional(),
      outputDir: z.string().optional(),
      limit: z.number().int().positive().max(100).optional(),
      recentEventsLimit: z.number().int().positive().max(1000).optional().describe('Maximum number of recent event entries (from events.jsonl) to summarize in single mode. Safe maximum is 1000; omitted means no event summaries are requested beyond defaults.'),
      staleHeartbeatMs: z.number().int().positive().optional().describe('Heartbeat age threshold for stalled detection.'),
      slowEventMs: z.number().int().positive().optional().describe('Event age threshold for slow detection.'),
      includeControllerSummary: z.boolean().optional().describe('Set false to omit controllerSummary from status responses.'),
    },
    outputSchema: statusOutputShape,
  },
  async (input) => {
    try {
      return jsonToolResult(await loadRunStatus(input))
    } catch (error) {
      return errorToolResult(error, 'status_failed')
    }
  },
)

server.registerTool(
  'subagent_cancel',
  {
    title: 'Cancel Active Subagent Run',
    description: 'Best-effort cancellation for Claude processes currently active in this MCP server process. Returns { runId, cancelledProcesses }.',
    inputSchema: {
      runId: z.string().min(1),
    },
    outputSchema: cancelOutputShape,
  },
  async (input) => {
    try {
      return jsonToolResult(await cancelRun(input.runId))
    } catch (error) {
      return errorToolResult(error, 'cancel_failed')
    }
  },
)

const transport = new StdioServerTransport()
await server.connect(transport)

function pickRunOptions(input) {
  return {
    workspace: input.workspace,
    outputDir: input.outputDir,
    concurrency: input.concurrency,
    dryRun: input.dryRun,
    claudeExecutable: input.claudeExecutable,
    claudeBaseArgs: input.claudeBaseArgs,
    env: input.env,
  }
}

function pickTaskFields(input) {
  return {
    model: input.model,
    effort: input.effort,
    timeoutMs: input.timeoutMs,
    permissionMode: input.permissionMode,
    addDirs: input.addDirs,
    allowedTools: input.allowedTools,
    disallowedTools: input.disallowedTools,
    tools: input.tools,
    systemPrompt: input.systemPrompt,
  }
}

function jsonToolResult(data) {
  const payload = { ok: true, ...data }
  return {
    structuredContent: payload,
    content: [
      {
        type: 'text',
        text: JSON.stringify(payload, null, 2),
      },
    ],
  }
}

// Structured error result. isError=true tells the client the tool failed while
// still returning a machine-readable error object in structuredContent; the SDK
// skips output-schema validation for isError results, so the error envelope is
// not constrained by the success outputSchema.
function errorToolResult(error, code) {
  const message = error instanceof Error ? error.message : String(error)
  const payload = {
    ok: false,
    error: {
      code: code || 'tool_error',
      message,
      ...(error instanceof Error && error.stack ? { stack: error.stack } : {}),
    },
  }
  return {
    isError: true,
    structuredContent: payload,
    content: [
      {
        type: 'text',
        text: JSON.stringify(payload, null, 2),
      },
    ],
  }
}
